/**
 * `_headers` for the static build.
 *
 * Cloudflare Pages reads this file and applies it to everything it serves —
 * which is every page of the site except the four the router renders. Those
 * carry the same headers in code (`SECURITY_HEADERS`), so a request gets the
 * same protection whichever half answered it.
 *
 * Kept as one exported constant rather than two files so the two cannot drift.
 */

import { SECURITY_HEADERS } from '../http/router.ts';

export function headersFile(): string {
  const lines = Object.entries(SECURITY_HEADERS).map(([name, value]) => `  ${name}: ${value}`);
  return [
    '# Generated by the build. Edit src/site/headers.ts, not this file.',
    '/*',
    ...lines,
    '',
  ].join('\n');
}
